EvergreenTown_RivalHouse_1F_MapScripts::
	.byte 0


EvergreenTown_RivalHouse_1F_NPCScript_Dad::
# 6 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	lock
# 7 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	faceplayer
# 8 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_1F_NPCScript_Dad_Text_0
# 9 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_1F_SignScript_Refrigerator::
# 16 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	lock
# 17 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_1F_SignScript_Refrigerator_Text_0
# 18 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_1F_SignScript_TV::
# 24 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	lock
# 25 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_1F_SignScript_TV_Text_0
# 26 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_1F_SignScript_Notebook::
# 32 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	lock
# 33 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_1F_SignScript_Notebook_Text_0
# 34 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_1F_SignScript_DadPC::
# 40 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	lock
# 41 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_1F_SignScript_DadPC_Text_0
# 42 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_1F_NPCScript_Dad_Text_0:
# 8 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	.string "Welcome {PLAYER}, thanks for\n"
	.string "stopping by. I really appreciate you\l"
	.string "being such a good friend to my boy.\p"
	.string "Good luck, though as a father, I do have\n"
	.string "to root for him for the league\l"
	.string "challenge.$"

EvergreenTown_RivalHouse_1F_SignScript_Refrigerator_Text_0:
# 17 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	.string "This is stocked up to the brim!$"

EvergreenTown_RivalHouse_1F_SignScript_TV_Text_0:
# 25 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	.string "Star Trek: The Next Generation is on\n"
	.string "the TV right now. Very good show.$"

EvergreenTown_RivalHouse_1F_SignScript_Notebook_Text_0:
# 33 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	.string "This notebook is filled with notes on\n"
	.string "all kinds of space based topics. Very\l"
	.string "cool indeed!$"

EvergreenTown_RivalHouse_1F_SignScript_DadPC_Text_0:
# 41 "data/maps/EvergreenTown_RivalHouse_1F/scripts.pory"
	.string "There's a simulation of a black hole\n"
	.string "running on this PC. That must have been\l"
	.string "hard to code up!$"
