EvergreenTown_RivalHouse_2F_MapScripts::
	.byte 0


EvergreenTown_RivalHouse_2F_NPCScript_Rival::
# 6 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	lock
# 7 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	faceplayer
# 8 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_2F_NPCScript_Rival_Text_0
# 9 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_2F_SignScript_Gamecube::
# 16 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	lock
# 17 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_2F_SignScript_Gamecube_Text_0
# 18 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_2F_SignScript_TV::
# 24 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	lock
# 25 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_2F_SignScript_TV_Text_0
# 26 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_2F_SignScript_RivalPC::
# 32 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	lock
# 33 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_2F_SignScript_RivalPC_Text_0
# 34 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_2F_SignScript_Notebook::
# 40 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	lock
# 41 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	msgbox EvergreenTown_RivalHouse_2F_SignScript_Notebook_Text_0
# 42 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	release
	end


EvergreenTown_RivalHouse_2F_NPCScript_Rival_Text_0:
# 8 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	.string "Jackson: Hey {PLAYER}, what are you\n"
	.string "doing here instead of at the lab?\p"
	.string "I'm just getting my exercise in before\n"
	.string "we have our battle.\p"
	.string "Go see the professor so you're not\n"
	.string "keeping him waiting.$"

EvergreenTown_RivalHouse_2F_SignScript_Gamecube_Text_0:
# 17 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	.string "Super Smash Bros. Melee is in the system\n"
	.string "right now. It's a really fun game!$"

EvergreenTown_RivalHouse_2F_SignScript_TV_Text_0:
# 25 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	.string "Dragon Ball Z seems to be on right now.\n"
	.string "Gohan just clapped Perfect Cell.$"

EvergreenTown_RivalHouse_2F_SignScript_RivalPC_Text_0:
# 33 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	.string "His steam library is open right now and\n"
	.string "there's a lot of games on here.$"

EvergreenTown_RivalHouse_2F_SignScript_Notebook_Text_0:
# 41 "data/maps/EvergreenTown_RivalHouse_2F/scripts.pory"
	.string "There seems to be all kinds of\n"
	.string "strategies for Pokemon battling in\l"
	.string "here.$"
